name: "Commit files"
description: "Commit files to the repository"
inputs:
  files:
    description: "List of filenames with path to the files to commit, separated by a comma"
    required: true
  commitMessage:
    description: "Commit message"
    default: "Commit from bot"
    required: true
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Commit
      shell: bash
      run: |
        bash "$GITHUB_ACTION_PATH/scripts/commit.sh"
      env:
        REPOSITORY: "${{ github.repository }}"
        REF_NAME: "${{ github.ref_name }}"
        FILES: "${{ inputs.files }}"
        COMMIT_MESSAGE: "${{ inputs.commitMessage }}"
        GH_AUTH_TOKEN: "${{ inputs.token }}"
